/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example manager@airmada.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @example password123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login berhasil */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            access_token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undang user baru (manager only) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        role: components["schemas"]["UserRole"];
                        full_name: string;
                    };
                };
            };
            responses: {
                /** @description Undangan terkirim */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            user_id?: string;
                            message?: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil user saat ini */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profil sendiri */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        full_name?: string;
                        phone?: string;
                        avatar_url?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List kendaraan */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["VehicleStatus"];
                    type?: components["schemas"]["VehicleType"];
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Vehicle"][];
                            total?: number;
                            page?: number;
                            limit?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Registrasi kendaraan baru (manager) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example AB 1234 CD */
                        plate_number: string;
                        type: components["schemas"]["VehicleType"];
                        /** @example 500 */
                        capacity_kg: number;
                        /** @example 2.5 */
                        capacity_volume_m3: number;
                        /** @example Bensin */
                        fuel_type: string;
                        /** @example 2022 */
                        year: number;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Kendaraan berhasil dibuat */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Detail kendaraan + riwayat rute */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            plate_number?: string;
                            type?: components["schemas"]["VehicleType"];
                            capacity_kg?: number;
                            capacity_volume_m3?: number;
                            status?: components["schemas"]["VehicleStatus"];
                            fuel_type?: string;
                            year?: number;
                            notes?: string | null;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                            recent_routes?: components["schemas"]["Route"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Soft delete kendaraan (manager) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update kendaraan (manager) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status?: components["schemas"]["VehicleStatus"];
                        capacity_kg?: number;
                        capacity_volume_m3?: number;
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/vehicles/{id}/gps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Riwayat GPS kendaraan */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            logs?: components["schemas"]["GpsLog"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supir */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["DriverStatus"];
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Driver"][];
                            total?: number;
                            page?: number;
                            limit?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Tambah supir baru (manager) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        full_name: string;
                        phone: string;
                        license_number: string;
                        /** Format: date */
                        license_expiry: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            driver?: components["schemas"]["Driver"];
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Detail supir + statistik performa */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            user_id?: string;
                            /** Format: uuid */
                            vehicle_id?: string | null;
                            license_number?: string;
                            /** Format: date */
                            license_expiry?: string;
                            status?: components["schemas"]["DriverStatus"];
                            total_deliveries?: number;
                            rating?: number;
                            user?: components["schemas"]["User"];
                            stats?: components["schemas"]["DriverPerformance"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update supir, assign/unassign kendaraan (manager) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        vehicle_id?: string | null;
                        status?: components["schemas"]["DriverStatus"];
                        /** Format: date */
                        license_expiry?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/drivers/{id}/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Riwayat pengiriman supir */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                    status?: components["schemas"]["ShipmentStatus"];
                    page?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Shipment"][];
                            total?: number;
                            page?: number;
                            limit?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drivers/{id}/performance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Analytics performa supir (manager) */
        get: {
            parameters: {
                query?: {
                    period?: "7d" | "30d" | "90d";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DriverPerformance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List paket */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["ShipmentStatus"];
                    driver_id?: string;
                    priority?: components["schemas"]["ShipmentPriority"];
                    date_from?: string;
                    date_to?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Shipment"][];
                            total?: number;
                            page?: number;
                            limit?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Buat paket baru (tracking code otomatis) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example PT Maju Jaya */
                        sender_name: string;
                        /** @example Jl. Sudirman No. 1, Jakarta */
                        sender_address: string;
                        /** @example Budi Santoso */
                        recipient_name: string;
                        /** @example Jl. Malioboro No. 10, Yogyakarta */
                        recipient_address: string;
                        /** @example -7.7956 */
                        recipient_lat: number;
                        /** @example 110.3695 */
                        recipient_lng: number;
                        /** @example 5.5 */
                        weight_kg: number;
                        /** @example 0.02 */
                        volume_m3: number;
                        priority?: components["schemas"]["ShipmentPriority"];
                        notes?: string;
                    };
                };
            };
            responses: {
                /** @description Paket berhasil dibuat */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shipment"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/track/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        /** Tracking publik via kode (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tracking_code?: string;
                            status?: components["schemas"]["ShipmentStatus"];
                            /** Format: date-time */
                            estimated_delivery?: string | null;
                            /** Format: date-time */
                            actual_delivery?: string | null;
                            status_logs?: components["schemas"]["ShipmentStatusLog"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Detail paket + timeline status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            tracking_code?: string;
                            /** Format: uuid */
                            driver_id?: string | null;
                            /** Format: uuid */
                            route_id?: string | null;
                            status?: components["schemas"]["ShipmentStatus"];
                            sender_name?: string;
                            sender_address?: string;
                            recipient_name?: string;
                            recipient_address?: string;
                            recipient_lat?: number;
                            recipient_lng?: number;
                            weight_kg?: number;
                            volume_m3?: number;
                            priority?: components["schemas"]["ShipmentPriority"];
                            /** Format: date-time */
                            estimated_delivery?: string | null;
                            /** Format: date-time */
                            actual_delivery?: string | null;
                            failure_reason?: string | null;
                            notes?: string | null;
                            /** Format: date-time */
                            created_at?: string;
                            /** Format: date-time */
                            updated_at?: string;
                            status_logs?: components["schemas"]["ShipmentStatusLog"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Hapus paket (hanya status pending, manager) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update status paket (FSM) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["ShipmentStatus"];
                        note?: string;
                        location_lat?: number;
                        location_lng?: number;
                        /** @description Wajib diisi jika status = failed */
                        failure_reason?: string;
                    };
                };
            };
            responses: {
                /** @description Status diperbarui */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            shipment?: components["schemas"]["Shipment"];
                            log?: components["schemas"]["ShipmentStatusLog"];
                        };
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/api/shipments/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign paket ke driver dan route */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        driver_id: string;
                        /** Format: uuid */
                        route_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Shipment"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rute */
        get: {
            parameters: {
                query?: {
                    date?: string;
                    status?: components["schemas"]["RouteStatus"];
                    vehicle_id?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Route"][];
                            total?: number;
                            page?: number;
                            limit?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Buat rute baru (otomatis trigger AI optimasi) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        vehicle_id: string;
                        /** Format: uuid */
                        driver_id: string;
                        /** Format: date */
                        date: string;
                        shipment_ids: string[];
                        /** @example -7.7983 */
                        origin_lat: number;
                        /** @example 110.3717 */
                        origin_lng: number;
                    };
                };
            };
            responses: {
                /** @description Rute dibuat dengan waypoints teroptimasi */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Detail rute + list shipment terurut */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            /** Format: uuid */
                            vehicle_id?: string;
                            /** Format: uuid */
                            driver_id?: string;
                            /** Format: date */
                            date?: string;
                            status?: components["schemas"]["RouteStatus"];
                            origin_lat?: number;
                            origin_lng?: number;
                            waypoints?: components["schemas"]["Waypoint"][];
                            optimized_distance_km?: number | null;
                            estimated_duration_min?: number | null;
                            /** Format: date-time */
                            started_at?: string | null;
                            /** Format: date-time */
                            completed_at?: string | null;
                            shipments?: components["schemas"]["Shipment"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update status rute (start / complete / cancel) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["RouteStatus"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/routes/{id}/reoptimize": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Re-run AI optimasi rute */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        shipment_ids: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/gps/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kirim koordinat GPS (driver, tiap ~5 detik) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example -7.7956 */
                        lat: number;
                        /** @example 110.3695 */
                        lng: number;
                        /** @example 42.5 */
                        speed_kmh: number;
                        /**
                         * @description Arah kendaraan 0-360 derajat
                         * @example 180
                         */
                        heading: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Posisi terkini semua kendaraan aktif */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            vehicles?: {
                                /** Format: uuid */
                                vehicle_id?: string;
                                plate?: string;
                                driver_name?: string;
                                lat?: number;
                                lng?: number;
                                speed_kmh?: number;
                                heading?: number;
                                /** Format: date-time */
                                updated_at?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gps/history/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vehicleId: string;
            };
            cookie?: never;
        };
        /** Riwayat GPS untuk playback rute */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path: {
                    vehicleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            logs?: components["schemas"]["GpsLog"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List notifikasi user saat ini */
        get: {
            parameters: {
                query?: {
                    is_read?: boolean;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Notification"][];
                            unread_count?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tandai semua notifikasi sudah dibaca */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updated_count?: number;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Tandai satu notifikasi sudah dibaca */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success?: boolean;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chatbot — query natural language tentang data armada */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Berapa paket yang belum terkirim hari ini? */
                        message: string;
                        conversation_history?: {
                            /** @enum {string} */
                            role?: "user" | "assistant";
                            content?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reply?: string;
                            sources?: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/optimize-route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimasi urutan titik pengiriman */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        origin: {
                            lat?: number;
                            lng?: number;
                        };
                        destinations: {
                            lat?: number;
                            lng?: number;
                            /** Format: uuid */
                            shipment_id?: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Rute teroptimasi */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ordered_waypoints?: {
                                lat?: number;
                                lng?: number;
                                /** Format: uuid */
                                shipment_id?: string;
                            }[];
                            estimated_distance_km?: number;
                            estimated_duration_min?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/predict-eta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prediksi ETA untuk shipment tertentu */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        route_id: string;
                        /** Format: uuid */
                        shipment_id: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: date-time */
                            estimated_arrival?: string;
                            /** @example 0.85 */
                            confidence?: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Anomali terdeteksi hari ini */
        get: {
            parameters: {
                query?: {
                    severity?: components["schemas"]["AnomalySeverity"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            anomalies?: components["schemas"]["AnomalyItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/generate-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate narasi laporan performa via AI (manager) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date_from: string;
                        /** Format: date */
                        date_to: string;
                        /**
                         * @default summary
                         * @enum {string}
                         */
                        format?: "summary" | "detailed";
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            narrative_text?: string;
                            data?: components["schemas"]["DashboardKpi"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI utama hari ini */
        get: {
            parameters: {
                query?: {
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardKpi"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tren performa dalam rentang waktu */
        get: {
            parameters: {
                query: {
                    date_from: string;
                    date_to: string;
                    group_by?: "day" | "week" | "month";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            series?: {
                                date?: string;
                                delivered?: number;
                                failed?: number;
                                on_time_rate?: number;
                                total?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data heatmap area pengiriman */
        get: {
            parameters: {
                query?: {
                    date_from?: string;
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            points?: {
                                lat?: number;
                                lng?: number;
                                weight?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranking performa semua supir */
        get: {
            parameters: {
                query?: {
                    period?: "7d" | "30d" | "90d";
                    sort?: "success_rate" | "total_deliveries" | "on_time_rate";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            drivers?: {
                                /** Format: uuid */
                                id?: string;
                                name?: string;
                                total_deliveries?: number;
                                success_rate?: number;
                                on_time_rate?: number;
                                avg_delivery_time_min?: number;
                                failed_deliveries?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export laporan ke CSV / XLSX / PDF */
        get: {
            parameters: {
                query: {
                    format: "csv" | "xlsx" | "pdf";
                    type: "shipments" | "drivers" | "vehicles";
                    date_from?: string;
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            download_url?: string;
                            /** Format: date-time */
                            expires_at?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "manager" | "dispatcher" | "driver";
        /** @enum {string} */
        VehicleType: "motor" | "pickup" | "van" | "truck";
        /** @enum {string} */
        VehicleStatus: "idle" | "active" | "maintenance" | "offline";
        /** @enum {string} */
        DriverStatus: "available" | "on_duty" | "off" | "suspended";
        /** @enum {string} */
        ShipmentStatus: "pending" | "assigned" | "pickup" | "in_transit" | "delivered" | "failed" | "returned";
        /** @enum {string} */
        ShipmentPriority: "regular" | "express" | "same_day";
        /** @enum {string} */
        RouteStatus: "planned" | "active" | "completed" | "cancelled";
        /** @enum {string} */
        NotifType: "alert" | "info" | "warning" | "success";
        /** @enum {string} */
        AnomalySeverity: "low" | "medium" | "high";
        /** @enum {string} */
        AnomalyType: "route_deviation" | "gps_silent" | "late_delivery" | "speed_anomaly";
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            role?: components["schemas"]["UserRole"];
            phone?: string | null;
            avatar_url?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        Vehicle: {
            /** Format: uuid */
            id?: string;
            /** @example AB 1234 CD */
            plate_number?: string;
            type?: components["schemas"]["VehicleType"];
            /** @example 500 */
            capacity_kg?: number;
            /** @example 2.5 */
            capacity_volume_m3?: number;
            status?: components["schemas"]["VehicleStatus"];
            /** @example Bensin */
            fuel_type?: string;
            /** @example 2022 */
            year?: number;
            notes?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Driver: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            vehicle_id?: string | null;
            license_number?: string;
            /** Format: date */
            license_expiry?: string;
            status?: components["schemas"]["DriverStatus"];
            total_deliveries?: number;
            /** @example 4.8 */
            rating?: number;
            user?: components["schemas"]["User"];
        };
        Shipment: {
            /** Format: uuid */
            id?: string;
            /** @example ARM-2024-AB1CD */
            tracking_code?: string;
            /** Format: uuid */
            driver_id?: string | null;
            /** Format: uuid */
            route_id?: string | null;
            status?: components["schemas"]["ShipmentStatus"];
            sender_name?: string;
            sender_address?: string;
            recipient_name?: string;
            recipient_address?: string;
            /** @example -7.7956 */
            recipient_lat?: number;
            /** @example 110.3695 */
            recipient_lng?: number;
            /** @example 5.5 */
            weight_kg?: number;
            /** @example 0.02 */
            volume_m3?: number;
            priority?: components["schemas"]["ShipmentPriority"];
            /** Format: date-time */
            estimated_delivery?: string | null;
            /** Format: date-time */
            actual_delivery?: string | null;
            failure_reason?: string | null;
            notes?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ShipmentStatusLog: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            shipment_id?: string;
            old_status?: string;
            new_status?: string;
            /** Format: uuid */
            changed_by?: string;
            note?: string | null;
            location_lat?: number | null;
            location_lng?: number | null;
            /** Format: date-time */
            created_at?: string;
        };
        Waypoint: {
            lat?: number;
            lng?: number;
            /** Format: uuid */
            shipment_id?: string;
            order?: number;
            /** Format: date-time */
            eta?: string | null;
        };
        Route: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            vehicle_id?: string;
            /** Format: uuid */
            driver_id?: string;
            /** Format: date */
            date?: string;
            status?: components["schemas"]["RouteStatus"];
            origin_lat?: number;
            origin_lng?: number;
            waypoints?: components["schemas"]["Waypoint"][];
            optimized_distance_km?: number | null;
            estimated_duration_min?: number | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
        };
        GpsLog: {
            id?: number;
            /** Format: uuid */
            vehicle_id?: string;
            /** Format: uuid */
            driver_id?: string;
            lat?: number;
            lng?: number;
            speed_kmh?: number;
            heading?: number;
            /** Format: date-time */
            recorded_at?: string;
        };
        Notification: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string;
            type?: components["schemas"]["NotifType"];
            title?: string;
            message?: string;
            related_entity?: string | null;
            /** Format: uuid */
            related_id?: string | null;
            is_read?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        AnomalyItem: {
            /** Format: uuid */
            vehicle_id?: string;
            type?: components["schemas"]["AnomalyType"];
            severity?: components["schemas"]["AnomalySeverity"];
            description?: string;
            confidence?: number;
            /** Format: date-time */
            detected_at?: string;
        };
        DashboardKpi: {
            total_shipments?: number;
            delivered?: number;
            failed?: number;
            in_transit?: number;
            pending?: number;
            active_vehicles?: number;
            success_rate?: number;
            on_time_rate?: number;
            avg_delivery_time_min?: number;
        };
        DriverPerformance: {
            total_deliveries?: number;
            success_rate?: number;
            on_time_rate?: number;
            avg_delivery_time_min?: number;
            failed_deliveries?: number;
        };
        ErrorResponse: {
            error: string;
            code?: string | null;
        };
    };
    responses: {
        /** @description Token tidak valid atau tidak ada */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Role tidak memiliki akses */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource tidak ditemukan */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Validasi gagal atau transisi FSM tidak valid */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
